#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
[[ -s "${ZDOTDIR:-$HOME}/.profile" ]] && source "${ZDOTDIR:-$HOME}/.profile"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# test -e "${HOME}/develop/zsh-autosuggestions" && source "${HOME}/develop/zsh-autosuggestions/zsh-autosuggestions.zsh"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/user/develop/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/user/develop/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/user/develop/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/user/develop/google-cloud-sdk/completion.zsh.inc'; fi
